# Generated by Django 4.0.6 on 2022-08-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_author', models.BooleanField()),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField()),
                ('post_title', models.CharField(max_length=250)),
                ('post_text', models.TextField()),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniblog.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField()),
                ('comment_text', models.TextField()),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniblog.bloguser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniblog.post')),
            ],
        ),
    ]
