# Generated by Django 4.0.6 on 2022-08-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='is_author',
        ),
    ]
